# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- hosts: all
  gather_facts: false
  collections:
    - ibm.power_ibmi

  tasks:
  - name: delete user profile
    ibmi_user_and_group:
      operation: 'delete'
      user: 'ansible'
      parameters: "OWNOBJOPT(*CHGOWN QSECOFR)"
  
